name: CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        os: [ubuntu-20.04, ubuntu-22.04]
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y gzip util-linux parted
    
    - name: Check script syntax
      run: |
        bash -n wic-editor.sh
    
    - name: Run shellcheck
      run: |
        sudo apt-get install -y shellcheck
        shellcheck wic-editor.sh
    
    - name: Test help output (requires sudo)
      run: |
        sudo ./wic-editor.sh -h
    
    - name: Test invalid arguments (requires sudo)
      run: |
        # This should fail with exit code 1 (missing arguments)
        if sudo ./wic-editor.sh; then
          echo "Script should fail with missing arguments"
          exit 1
        else
          echo "Script correctly failed with missing arguments"
        fi
    
    - name: Test partition listing (with dummy image)
      run: |
        # Create a minimal test WIC image for testing
        dd if=/dev/zero of=test.wic bs=1M count=100
        # Create a simple partition table
        parted -s test.wic mklabel msdos
        parted -s test.wic mkpart primary ext4 1MB 99MB
        
        # Test partition listing
        sudo ./wic-editor.sh -i test.wic -p list || echo "Expected to fail on test image"
        
        # Cleanup
        rm -f test.wic
